version: "3.8"
services:
  board-service-database:
    container_name: board-service-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: chungjm0711/board-service-database
    environment:
      - MYSQL_DATABASE=board_db
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"
