version: "3.8"
services:
  board-service-database:
    container_name: board-service-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - ${DB_PORT}:3306
